[build]
  # Comando para gerar os arquivos de produção do Angular
  command = "ng build --configuration production"
  
  # Diretório onde o Angular vai gerar os arquivos finais
  publish = "dist/despachante-digital"
  command = "ng build"
  publish = "dist/despachante-digital/browser"

# Configurações para limpar cache e usar Node.js moderno
[context.production.environment]
  NODE_VERSION = "20"

# Opcional: redirecionamento de todas as rotas para index.html (Angular SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"